<?= $this->doctype(); ?>

<html>
    <head>
        <?= $this->headTitle(); ?>

        <?= $this->headMeta(); ?>


        <?= $this->headLink()->appendStylesheet('/css/style.css'); ?>


        <?php
        echo $this->headScript()->appendFile('/plugin/jquery/jquery.js')
                ->appendFile('/js/main.js');
        ?>

    </head>
    <body>
        <?= $this->layout()->content; ?>
    </body>
</html>