<?= $this->doctype(); ?>

<html>
    <head>
        <?= $this->headTitle(); ?>

        <?= $this->headMeta(); ?>


        <?= $this->headLink()->appendStylesheet('/plugin/jquery/jquery-ui.css')
                ->appendStylesheet('/backend/css/style.css'); ?>


        <?php
        echo $this->headScript()->appendFile('/plugin/jquery/jquery.js')
                ->appendFile('/plugin/jquery/jquery-ui.js')
                ->appendFile('/backend/js/main.js');
        ?>

    </head>
    <body>
        <?= $this->layout()->content; ?>
        
    </body>
</html>